export const Images = {
  splash_sc: require('../assets/splash_sc.png'),
  onboard_sc: require('../assets/onboard_sc.png'),
  chicken_logo: require('../assets/chicken_logo.png'),
  chicken: require('../assets/chicken.jpg'),
  burger_logo: require('../assets/burger_logo.png'),
  burger: require('../assets/burger.jpg'),
  pizza: require('../assets/Pizza.jpg'),
  burger_French_fries: require('../assets/burger_French_Fries.jpg'),
  biriyani: require('../assets/chicken_biryani.jpg'),
  Tteok_bokki: require('../assets/Tteok_bokki.jpeg'),
  Croissants: require('../assets/Croissants.jpg'),
  Macarons: require('../assets/Chocolate_Macarons.jpg'),
  dessert: require('../assets/dessert.jpg'),
  nasi_lemak: require('../assets/nasi_lemak.jpg'),
  mochi: require('../assets/Mochi.jpg'),
  Corn_dog: require('../assets/Corn_dog.jpeg'),
  cart: require('../assets/cart.png'),
};
